language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit

after_success:
  - echo 'Build succeeded.'

after_failure:
  - echo 'Build failed.'
